services:

    _defaults:
        autowire: true
        autoconfigure: true

    EB\PlantUMLBundle\Command\:
        resource: '../../Command/*.php'
    EB\PlantUMLBundle\Drawer\:
        resource: '../../Drawer/*.php'
    EB\PlantUMLBundle\Drawer\PlantUML:
        $java: '%eb.plant_uml_bundle.java%'
